### ISSUE TITLE
Add Context Path to HtmxResponse browser redirect

### ISSUE THREAD

**Issue by sthato** [wimdeblauwe/htmx-spring-boot-thymeleaf#45]
If I have setup a context path on my application.yml
`server.servlet.context-path: /bot-webapp` if I return `new HtmxResponse().browserRedirect("/")` , it doesn't automatically add the context path. I have to manually add it to the return ` new HtmxResponse().browserRedirect("/bot-webapp")`

**Comment by klu2** [comment]
I would not implement that, the `org.springframework.web.servlet.view.RedirectView` also does not consider the `server.servlet.context-path`

In your above example, if you do that

````java
@GetMapping("/redirect")
public View redirect() {
    return new RedirectView("/redirect-target");
}
````

And you then perform `GET /bot-webapp/redirect` then your target will be `/redirect-target` instead of `/bot-webapp/redirect-target` - you would need to add the `context-path` parameter here as well.

So I'd stick with the default behaviour of Spring MVC here.

**Comment by wimdeblauwe** [comment]
Thanks for this information @klu2 I will indeed align with the default behaviour of Spring MVC.
